//---------------------------------------------------------------------
// File: BamManagementService.cs
// 
// Sample: OperationsOM
//
//---------------------------------------------------------------------
// This file is part of the Microsoft BizTalk Server SDK
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//
// This source code is intended only as a supplement to Microsoft BizTalk
// Server 2016 release and/or on-line documentation. See these other
// materials for detailed information regarding Microsoft code samples.
//
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
// KIND, WHETHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
// PURPOSE.
//---------------------------------------------------------------------





//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.26
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.26.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BamManagementServiceSoap", Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public partial class BamManagementService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback AddSubscriptionOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateAlertOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteAlertOperationCompleted;
    
    private System.Threading.SendOrPostCallback GenerateEventForArtifactOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetAlertOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetAlertsSummaryOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetCapabilitiesOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetPivotViewXmlOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetRelatedActivityInstancesOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetReferencesOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetViewDetailsAsXmlOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetViewSummaryForCurrentUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback RemoveSubscriptionOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateAlertOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateSubscriptionOperationCompleted;
    
    /// <remarks/>
    public BamManagementService() {
        this.Url = "http://localhost/bam/bammanagementservice/bammanagementservice.asmx";
    }
    
    /// <remarks/>
    public event AddSubscriptionCompletedEventHandler AddSubscriptionCompleted;
    
    /// <remarks/>
    public event CreateAlertCompletedEventHandler CreateAlertCompleted;
    
    /// <remarks/>
    public event DeleteAlertCompletedEventHandler DeleteAlertCompleted;
    
    /// <remarks/>
    public event GenerateEventForArtifactCompletedEventHandler GenerateEventForArtifactCompleted;
    
    /// <remarks/>
    public event GetAlertCompletedEventHandler GetAlertCompleted;
    
    /// <remarks/>
    public event GetAlertsSummaryCompletedEventHandler GetAlertsSummaryCompleted;
    
    /// <remarks/>
    public event GetCapabilitiesCompletedEventHandler GetCapabilitiesCompleted;
    
    /// <remarks/>
    public event GetPivotViewXmlCompletedEventHandler GetPivotViewXmlCompleted;
    
    /// <remarks/>
    public event GetRelatedActivityInstancesCompletedEventHandler GetRelatedActivityInstancesCompleted;
    
    /// <remarks/>
    public event GetReferencesCompletedEventHandler GetReferencesCompleted;
    
    /// <remarks/>
    public event GetViewDetailsAsXmlCompletedEventHandler GetViewDetailsAsXmlCompleted;
    
    /// <remarks/>
    public event GetViewSummaryForCurrentUserCompletedEventHandler GetViewSummaryForCurrentUserCompleted;
    
    /// <remarks/>
    public event RemoveSubscriptionCompletedEventHandler RemoveSubscriptionCompleted;
    
    /// <remarks/>
    public event UpdateAlertCompletedEventHandler UpdateAlertCompleted;
    
    /// <remarks/>
    public event UpdateSubscriptionCompletedEventHandler UpdateSubscriptionCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService/AddSu" +
        "bscription", RequestNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", ResponseNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void AddSubscription(string viewName, string alertName, Subscription[] subscriptions) {
        this.Invoke("AddSubscription", new object[] {
                    viewName,
                    alertName,
                    subscriptions});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAddSubscription(string viewName, string alertName, Subscription[] subscriptions, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AddSubscription", new object[] {
                    viewName,
                    alertName,
                    subscriptions}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndAddSubscription(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void AddSubscriptionAsync(string viewName, string alertName, Subscription[] subscriptions) {
        this.AddSubscriptionAsync(viewName, alertName, subscriptions, null);
    }
    
    /// <remarks/>
    public void AddSubscriptionAsync(string viewName, string alertName, Subscription[] subscriptions, object userState) {
        if ((this.AddSubscriptionOperationCompleted == null)) {
            this.AddSubscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddSubscriptionOperationCompleted);
        }
        this.InvokeAsync("AddSubscription", new object[] {
                    viewName,
                    alertName,
                    subscriptions}, this.AddSubscriptionOperationCompleted, userState);
    }
    
    private void OnAddSubscriptionOperationCompleted(object arg) {
        if ((this.AddSubscriptionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AddSubscriptionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService/Creat" +
        "eAlert", RequestNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", ResponseNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void CreateAlert(Alert Alert) {
        this.Invoke("CreateAlert", new object[] {
                    Alert});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateAlert(Alert Alert, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateAlert", new object[] {
                    Alert}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndCreateAlert(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void CreateAlertAsync(Alert Alert) {
        this.CreateAlertAsync(Alert, null);
    }
    
    /// <remarks/>
    public void CreateAlertAsync(Alert Alert, object userState) {
        if ((this.CreateAlertOperationCompleted == null)) {
            this.CreateAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAlertOperationCompleted);
        }
        this.InvokeAsync("CreateAlert", new object[] {
                    Alert}, this.CreateAlertOperationCompleted, userState);
    }
    
    private void OnCreateAlertOperationCompleted(object arg) {
        if ((this.CreateAlertCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateAlertCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService/Delet" +
        "eAlert", RequestNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", ResponseNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void DeleteAlert(string viewName, string alertName) {
        this.Invoke("DeleteAlert", new object[] {
                    viewName,
                    alertName});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteAlert(string viewName, string alertName, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteAlert", new object[] {
                    viewName,
                    alertName}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndDeleteAlert(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void DeleteAlertAsync(string viewName, string alertName) {
        this.DeleteAlertAsync(viewName, alertName, null);
    }
    
    /// <remarks/>
    public void DeleteAlertAsync(string viewName, string alertName, object userState) {
        if ((this.DeleteAlertOperationCompleted == null)) {
            this.DeleteAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAlertOperationCompleted);
        }
        this.InvokeAsync("DeleteAlert", new object[] {
                    viewName,
                    alertName}, this.DeleteAlertOperationCompleted, userState);
    }
    
    private void OnDeleteAlertOperationCompleted(object arg) {
        if ((this.DeleteAlertCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteAlertCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService/Gener" +
        "ateEventForArtifact", RequestNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", ResponseNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void GenerateEventForArtifact(string viewName, string title, string description, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] Reference[] References) {
        this.Invoke("GenerateEventForArtifact", new object[] {
                    viewName,
                    title,
                    description,
                    References});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGenerateEventForArtifact(string viewName, string title, string description, Reference[] References, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GenerateEventForArtifact", new object[] {
                    viewName,
                    title,
                    description,
                    References}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndGenerateEventForArtifact(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void GenerateEventForArtifactAsync(string viewName, string title, string description, Reference[] References) {
        this.GenerateEventForArtifactAsync(viewName, title, description, References, null);
    }
    
    /// <remarks/>
    public void GenerateEventForArtifactAsync(string viewName, string title, string description, Reference[] References, object userState) {
        if ((this.GenerateEventForArtifactOperationCompleted == null)) {
            this.GenerateEventForArtifactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateEventForArtifactOperationCompleted);
        }
        this.InvokeAsync("GenerateEventForArtifact", new object[] {
                    viewName,
                    title,
                    description,
                    References}, this.GenerateEventForArtifactOperationCompleted, userState);
    }
    
    private void OnGenerateEventForArtifactOperationCompleted(object arg) {
        if ((this.GenerateEventForArtifactCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GenerateEventForArtifactCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService/GetAl" +
        "ert", RequestNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", ResponseNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Alert GetAlert(string viewName, string alertName) {
        object[] results = this.Invoke("GetAlert", new object[] {
                    viewName,
                    alertName});
        return ((Alert)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetAlert(string viewName, string alertName, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetAlert", new object[] {
                    viewName,
                    alertName}, callback, asyncState);
    }
    
    /// <remarks/>
    public Alert EndGetAlert(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Alert)(results[0]));
    }
    
    /// <remarks/>
    public void GetAlertAsync(string viewName, string alertName) {
        this.GetAlertAsync(viewName, alertName, null);
    }
    
    /// <remarks/>
    public void GetAlertAsync(string viewName, string alertName, object userState) {
        if ((this.GetAlertOperationCompleted == null)) {
            this.GetAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAlertOperationCompleted);
        }
        this.InvokeAsync("GetAlert", new object[] {
                    viewName,
                    alertName}, this.GetAlertOperationCompleted, userState);
    }
    
    private void OnGetAlertOperationCompleted(object arg) {
        if ((this.GetAlertCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetAlertCompleted(this, new GetAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService/GetAl" +
        "ertsSummary", RequestNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", ResponseNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayAttribute("Alerts")]
    [return: System.Xml.Serialization.XmlArrayItemAttribute("AlertInstance", IsNullable=false)]
    public AlertSummary[] GetAlertsSummary(string viewName) {
        object[] results = this.Invoke("GetAlertsSummary", new object[] {
                    viewName});
        return ((AlertSummary[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetAlertsSummary(string viewName, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetAlertsSummary", new object[] {
                    viewName}, callback, asyncState);
    }
    
    /// <remarks/>
    public AlertSummary[] EndGetAlertsSummary(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((AlertSummary[])(results[0]));
    }
    
    /// <remarks/>
    public void GetAlertsSummaryAsync(string viewName) {
        this.GetAlertsSummaryAsync(viewName, null);
    }
    
    /// <remarks/>
    public void GetAlertsSummaryAsync(string viewName, object userState) {
        if ((this.GetAlertsSummaryOperationCompleted == null)) {
            this.GetAlertsSummaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAlertsSummaryOperationCompleted);
        }
        this.InvokeAsync("GetAlertsSummary", new object[] {
                    viewName}, this.GetAlertsSummaryOperationCompleted, userState);
    }
    
    private void OnGetAlertsSummaryOperationCompleted(object arg) {
        if ((this.GetAlertsSummaryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetAlertsSummaryCompleted(this, new GetAlertsSummaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService/GetCa" +
        "pabilities", RequestNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", ResponseNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Configuration GetCapabilities() {
        object[] results = this.Invoke("GetCapabilities", new object[0]);
        return ((Configuration)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetCapabilities(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetCapabilities", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public Configuration EndGetCapabilities(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Configuration)(results[0]));
    }
    
    /// <remarks/>
    public void GetCapabilitiesAsync() {
        this.GetCapabilitiesAsync(null);
    }
    
    /// <remarks/>
    public void GetCapabilitiesAsync(object userState) {
        if ((this.GetCapabilitiesOperationCompleted == null)) {
            this.GetCapabilitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCapabilitiesOperationCompleted);
        }
        this.InvokeAsync("GetCapabilities", new object[0], this.GetCapabilitiesOperationCompleted, userState);
    }
    
    private void OnGetCapabilitiesOperationCompleted(object arg) {
        if ((this.GetCapabilitiesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetCapabilitiesCompleted(this, new GetCapabilitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService/GetPi" +
        "votViewXml", RequestNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", ResponseNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetPivotViewXml(string viewName, string pivotViewName, string cubeName) {
        object[] results = this.Invoke("GetPivotViewXml", new object[] {
                    viewName,
                    pivotViewName,
                    cubeName});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetPivotViewXml(string viewName, string pivotViewName, string cubeName, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetPivotViewXml", new object[] {
                    viewName,
                    pivotViewName,
                    cubeName}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetPivotViewXml(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetPivotViewXmlAsync(string viewName, string pivotViewName, string cubeName) {
        this.GetPivotViewXmlAsync(viewName, pivotViewName, cubeName, null);
    }
    
    /// <remarks/>
    public void GetPivotViewXmlAsync(string viewName, string pivotViewName, string cubeName, object userState) {
        if ((this.GetPivotViewXmlOperationCompleted == null)) {
            this.GetPivotViewXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPivotViewXmlOperationCompleted);
        }
        this.InvokeAsync("GetPivotViewXml", new object[] {
                    viewName,
                    pivotViewName,
                    cubeName}, this.GetPivotViewXmlOperationCompleted, userState);
    }
    
    private void OnGetPivotViewXmlOperationCompleted(object arg) {
        if ((this.GetPivotViewXmlCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetPivotViewXmlCompleted(this, new GetPivotViewXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService/GetRe" +
        "latedActivityInstances", RequestNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", ResponseNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public RelatedActivities GetRelatedActivityInstances(string viewName, string activityName, string activityInstanceId) {
        object[] results = this.Invoke("GetRelatedActivityInstances", new object[] {
                    viewName,
                    activityName,
                    activityInstanceId});
        return ((RelatedActivities)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetRelatedActivityInstances(string viewName, string activityName, string activityInstanceId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetRelatedActivityInstances", new object[] {
                    viewName,
                    activityName,
                    activityInstanceId}, callback, asyncState);
    }
    
    /// <remarks/>
    public RelatedActivities EndGetRelatedActivityInstances(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((RelatedActivities)(results[0]));
    }
    
    /// <remarks/>
    public void GetRelatedActivityInstancesAsync(string viewName, string activityName, string activityInstanceId) {
        this.GetRelatedActivityInstancesAsync(viewName, activityName, activityInstanceId, null);
    }
    
    /// <remarks/>
    public void GetRelatedActivityInstancesAsync(string viewName, string activityName, string activityInstanceId, object userState) {
        if ((this.GetRelatedActivityInstancesOperationCompleted == null)) {
            this.GetRelatedActivityInstancesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRelatedActivityInstancesOperationCompleted);
        }
        this.InvokeAsync("GetRelatedActivityInstances", new object[] {
                    viewName,
                    activityName,
                    activityInstanceId}, this.GetRelatedActivityInstancesOperationCompleted, userState);
    }
    
    private void OnGetRelatedActivityInstancesOperationCompleted(object arg) {
        if ((this.GetRelatedActivityInstancesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetRelatedActivityInstancesCompleted(this, new GetRelatedActivityInstancesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService/GetRe" +
        "ferences", RequestNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", ResponseNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayAttribute("References")]
    [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Reference[] GetReferences(string viewName, string activityName, string activityInstanceId, string referenceType) {
        object[] results = this.Invoke("GetReferences", new object[] {
                    viewName,
                    activityName,
                    activityInstanceId,
                    referenceType});
        return ((Reference[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetReferences(string viewName, string activityName, string activityInstanceId, string referenceType, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetReferences", new object[] {
                    viewName,
                    activityName,
                    activityInstanceId,
                    referenceType}, callback, asyncState);
    }
    
    /// <remarks/>
    public Reference[] EndGetReferences(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Reference[])(results[0]));
    }
    
    /// <remarks/>
    public void GetReferencesAsync(string viewName, string activityName, string activityInstanceId, string referenceType) {
        this.GetReferencesAsync(viewName, activityName, activityInstanceId, referenceType, null);
    }
    
    /// <remarks/>
    public void GetReferencesAsync(string viewName, string activityName, string activityInstanceId, string referenceType, object userState) {
        if ((this.GetReferencesOperationCompleted == null)) {
            this.GetReferencesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReferencesOperationCompleted);
        }
        this.InvokeAsync("GetReferences", new object[] {
                    viewName,
                    activityName,
                    activityInstanceId,
                    referenceType}, this.GetReferencesOperationCompleted, userState);
    }
    
    private void OnGetReferencesOperationCompleted(object arg) {
        if ((this.GetReferencesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetReferencesCompleted(this, new GetReferencesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService/GetVi" +
        "ewDetailsAsXml", RequestNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", ResponseNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetViewDetailsAsXml(string viewName) {
        object[] results = this.Invoke("GetViewDetailsAsXml", new object[] {
                    viewName});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetViewDetailsAsXml(string viewName, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetViewDetailsAsXml", new object[] {
                    viewName}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetViewDetailsAsXml(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetViewDetailsAsXmlAsync(string viewName) {
        this.GetViewDetailsAsXmlAsync(viewName, null);
    }
    
    /// <remarks/>
    public void GetViewDetailsAsXmlAsync(string viewName, object userState) {
        if ((this.GetViewDetailsAsXmlOperationCompleted == null)) {
            this.GetViewDetailsAsXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetViewDetailsAsXmlOperationCompleted);
        }
        this.InvokeAsync("GetViewDetailsAsXml", new object[] {
                    viewName}, this.GetViewDetailsAsXmlOperationCompleted, userState);
    }
    
    private void OnGetViewDetailsAsXmlOperationCompleted(object arg) {
        if ((this.GetViewDetailsAsXmlCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetViewDetailsAsXmlCompleted(this, new GetViewDetailsAsXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService/GetVi" +
        "ewSummaryForCurrentUser", RequestNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", ResponseNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("Views")]
    public ViewSummaryList GetViewSummaryForCurrentUser() {
        object[] results = this.Invoke("GetViewSummaryForCurrentUser", new object[0]);
        return ((ViewSummaryList)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetViewSummaryForCurrentUser(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetViewSummaryForCurrentUser", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ViewSummaryList EndGetViewSummaryForCurrentUser(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ViewSummaryList)(results[0]));
    }
    
    /// <remarks/>
    public void GetViewSummaryForCurrentUserAsync() {
        this.GetViewSummaryForCurrentUserAsync(null);
    }
    
    /// <remarks/>
    public void GetViewSummaryForCurrentUserAsync(object userState) {
        if ((this.GetViewSummaryForCurrentUserOperationCompleted == null)) {
            this.GetViewSummaryForCurrentUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetViewSummaryForCurrentUserOperationCompleted);
        }
        this.InvokeAsync("GetViewSummaryForCurrentUser", new object[0], this.GetViewSummaryForCurrentUserOperationCompleted, userState);
    }
    
    private void OnGetViewSummaryForCurrentUserOperationCompleted(object arg) {
        if ((this.GetViewSummaryForCurrentUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetViewSummaryForCurrentUserCompleted(this, new GetViewSummaryForCurrentUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService/Remov" +
        "eSubscription", RequestNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", ResponseNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void RemoveSubscription(string viewName, string alertName, Subscription[] subscriptions) {
        this.Invoke("RemoveSubscription", new object[] {
                    viewName,
                    alertName,
                    subscriptions});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRemoveSubscription(string viewName, string alertName, Subscription[] subscriptions, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RemoveSubscription", new object[] {
                    viewName,
                    alertName,
                    subscriptions}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndRemoveSubscription(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void RemoveSubscriptionAsync(string viewName, string alertName, Subscription[] subscriptions) {
        this.RemoveSubscriptionAsync(viewName, alertName, subscriptions, null);
    }
    
    /// <remarks/>
    public void RemoveSubscriptionAsync(string viewName, string alertName, Subscription[] subscriptions, object userState) {
        if ((this.RemoveSubscriptionOperationCompleted == null)) {
            this.RemoveSubscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveSubscriptionOperationCompleted);
        }
        this.InvokeAsync("RemoveSubscription", new object[] {
                    viewName,
                    alertName,
                    subscriptions}, this.RemoveSubscriptionOperationCompleted, userState);
    }
    
    private void OnRemoveSubscriptionOperationCompleted(object arg) {
        if ((this.RemoveSubscriptionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RemoveSubscriptionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService/Updat" +
        "eAlert", RequestNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", ResponseNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void UpdateAlert(Alert Alert) {
        this.Invoke("UpdateAlert", new object[] {
                    Alert});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateAlert(Alert Alert, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateAlert", new object[] {
                    Alert}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndUpdateAlert(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void UpdateAlertAsync(Alert Alert) {
        this.UpdateAlertAsync(Alert, null);
    }
    
    /// <remarks/>
    public void UpdateAlertAsync(Alert Alert, object userState) {
        if ((this.UpdateAlertOperationCompleted == null)) {
            this.UpdateAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAlertOperationCompleted);
        }
        this.InvokeAsync("UpdateAlert", new object[] {
                    Alert}, this.UpdateAlertOperationCompleted, userState);
    }
    
    private void OnUpdateAlertOperationCompleted(object arg) {
        if ((this.UpdateAlertCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateAlertCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService/Updat" +
        "eSubscription", RequestNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", ResponseNamespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void UpdateSubscription(string viewName, string alertName, Subscription[] subscriptions) {
        this.Invoke("UpdateSubscription", new object[] {
                    viewName,
                    alertName,
                    subscriptions});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateSubscription(string viewName, string alertName, Subscription[] subscriptions, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateSubscription", new object[] {
                    viewName,
                    alertName,
                    subscriptions}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndUpdateSubscription(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void UpdateSubscriptionAsync(string viewName, string alertName, Subscription[] subscriptions) {
        this.UpdateSubscriptionAsync(viewName, alertName, subscriptions, null);
    }
    
    /// <remarks/>
    public void UpdateSubscriptionAsync(string viewName, string alertName, Subscription[] subscriptions, object userState) {
        if ((this.UpdateSubscriptionOperationCompleted == null)) {
            this.UpdateSubscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSubscriptionOperationCompleted);
        }
        this.InvokeAsync("UpdateSubscription", new object[] {
                    viewName,
                    alertName,
                    subscriptions}, this.UpdateSubscriptionOperationCompleted, userState);
    }
    
    private void OnUpdateSubscriptionOperationCompleted(object arg) {
        if ((this.UpdateSubscriptionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateSubscriptionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
public partial class Subscription {
    
    private string userNameField;
    
    private string addressField;
    
    private SubscriptionType typeField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SubscriptionType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
public enum SubscriptionType {
    
    /// <remarks/>
    email,
    
    /// <remarks/>
    file,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public partial class PivotView {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public partial class Aggregation {
    
    private PivotView[] pivotViewField;
    
    private AggregationType typeField;
    
    private string nameField;
    
    private string cubeNameField;
    
    private string rtaWindowField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PivotView")]
    public PivotView[] PivotView {
        get {
            return this.pivotViewField;
        }
        set {
            this.pivotViewField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AggregationType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CubeName {
        get {
            return this.cubeNameField;
        }
        set {
            this.cubeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string RtaWindow {
        get {
            return this.rtaWindowField;
        }
        set {
            this.rtaWindowField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public enum AggregationType {
    
    /// <remarks/>
    OLAP,
    
    /// <remarks/>
    RTA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public partial class ActivitySummary {
    
    private Aggregation[] aggregationField;
    
    private string nameField;
    
    private string serverField;
    
    private string databaseField;
    
    private string portalUrlField;
    
    private bool isRemoteField;
    
    public ActivitySummary() {
        this.isRemoteField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Aggregation")]
    public Aggregation[] Aggregation {
        get {
            return this.aggregationField;
        }
        set {
            this.aggregationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Server {
        get {
            return this.serverField;
        }
        set {
            this.serverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Database {
        get {
            return this.databaseField;
        }
        set {
            this.databaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PortalUrl {
        get {
            return this.portalUrlField;
        }
        set {
            this.portalUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool IsRemote {
        get {
            return this.isRemoteField;
        }
        set {
            this.isRemoteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public partial class ViewSummary {
    
    private ActivitySummary[] activityField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Activity")]
    public ActivitySummary[] Activity {
        get {
            return this.activityField;
        }
        set {
            this.activityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public partial class ViewSummaryList {
    
    private ViewSummary[] viewField;
    
    private bool partialResultsField;
    
    public ViewSummaryList() {
        this.partialResultsField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("View")]
    public ViewSummary[] View {
        get {
            return this.viewField;
        }
        set {
            this.viewField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool PartialResults {
        get {
            return this.partialResultsField;
        }
        set {
            this.partialResultsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public partial class ActivityInstances {
    
    private string[] instanceField;
    
    private string activityNameField;
    
    private string serverField;
    
    private string databaseField;
    
    private string portalUrlField;
    
    private bool isRemoteField;
    
    public ActivityInstances() {
        this.isRemoteField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Instance")]
    public string[] Instance {
        get {
            return this.instanceField;
        }
        set {
            this.instanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ActivityName {
        get {
            return this.activityNameField;
        }
        set {
            this.activityNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Server {
        get {
            return this.serverField;
        }
        set {
            this.serverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Database {
        get {
            return this.databaseField;
        }
        set {
            this.databaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PortalUrl {
        get {
            return this.portalUrlField;
        }
        set {
            this.portalUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool IsRemote {
        get {
            return this.isRemoteField;
        }
        set {
            this.isRemoteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public partial class RelatedActivities {
    
    private ActivityInstances[] activityInstancesField;
    
    private bool partialResultsField;
    
    public RelatedActivities() {
        this.partialResultsField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ActivityInstances")]
    public ActivityInstances[] ActivityInstances {
        get {
            return this.activityInstancesField;
        }
        set {
            this.activityInstancesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool PartialResults {
        get {
            return this.partialResultsField;
        }
        set {
            this.partialResultsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public partial class Transport {
    
    private AlertTransport nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AlertTransport Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public enum AlertTransport {
    
    /// <remarks/>
    File,
    
    /// <remarks/>
    Email,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public partial class Alerts {
    
    private Transport[] transportsField;
    
    private bool configuredField;
    
    public Alerts() {
        this.configuredField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Transport[] Transports {
        get {
            return this.transportsField;
        }
        set {
            this.transportsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Configured {
        get {
            return this.configuredField;
        }
        set {
            this.configuredField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public partial class OlapAggregations {
    
    private bool configuredField;
    
    public OlapAggregations() {
        this.configuredField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Configured {
        get {
            return this.configuredField;
        }
        set {
            this.configuredField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public partial class Configuration {
    
    private string databaseVersionField;
    
    private OlapAggregations olapAggregationsField;
    
    private Alerts alertsField;
    
    /// <remarks/>
    public string DatabaseVersion {
        get {
            return this.databaseVersionField;
        }
        set {
            this.databaseVersionField = value;
        }
    }
    
    /// <remarks/>
    public OlapAggregations OlapAggregations {
        get {
            return this.olapAggregationsField;
        }
        set {
            this.olapAggregationsField = value;
        }
    }
    
    /// <remarks/>
    public Alerts Alerts {
        get {
            return this.alertsField;
        }
        set {
            this.alertsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public partial class AlertSummary {
    
    private string nameField;
    
    private AlertType typeField;
    
    private string priorityField;
    
    private bool enabledField;
    
    private string securityField;
    
    private bool isOwnerField;
    
    private string createdByField;
    
    private System.DateTime creationDateField;
    
    private bool creationDateFieldSpecified;
    
    private System.DateTime lastModifiedDateField;
    
    private bool lastModifiedDateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AlertType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string Security {
        get {
            return this.securityField;
        }
        set {
            this.securityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsOwner {
        get {
            return this.isOwnerField;
        }
        set {
            this.isOwnerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string CreatedBy {
        get {
            return this.createdByField;
        }
        set {
            this.createdByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime CreationDate {
        get {
            return this.creationDateField;
        }
        set {
            this.creationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreationDateSpecified {
        get {
            return this.creationDateFieldSpecified;
        }
        set {
            this.creationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime LastModifiedDate {
        get {
            return this.lastModifiedDateField;
        }
        set {
            this.lastModifiedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LastModifiedDateSpecified {
        get {
            return this.lastModifiedDateFieldSpecified;
        }
        set {
            this.lastModifiedDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public enum AlertType {
    
    /// <remarks/>
    Instance,
    
    /// <remarks/>
    OLAP,
    
    /// <remarks/>
    RTA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public partial class Reference {
    
    private string typeField;
    
    private string nameField;
    
    private string dataField;
    
    private string longReferenceDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LongReferenceData {
        get {
            return this.longReferenceDataField;
        }
        set {
            this.longReferenceDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
public partial class TimeDurationSimple {
    
    private TimePartSimple unitField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TimePartSimple Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
public enum TimePartSimple {
    
    /// <remarks/>
    Week,
    
    /// <remarks/>
    Day,
    
    /// <remarks/>
    Hour,
    
    /// <remarks/>
    Minute,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
public partial class TimeWindow {
    
    private TimeDurationSimple timeWindowDurationField;
    
    private TimeDurationSimple incrementField;
    
    private bool enabledField;
    
    private string timeDimensionField;
    
    /// <remarks/>
    public TimeDurationSimple TimeWindowDuration {
        get {
            return this.timeWindowDurationField;
        }
        set {
            this.timeWindowDurationField = value;
        }
    }
    
    /// <remarks/>
    public TimeDurationSimple Increment {
        get {
            return this.incrementField;
        }
        set {
            this.incrementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TimeDimension {
        get {
            return this.timeDimensionField;
        }
        set {
            this.timeDimensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
public partial class Level {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
public partial class SlicerDimension {
    
    private Level[] levelField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Level")]
    public Level[] Level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
public partial class Threshold {
    
    private string nameField;
    
    private string conditionField;
    
    private double valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Condition {
        get {
            return this.conditionField;
        }
        set {
            this.conditionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
public partial class AggregationQuery {
    
    private Threshold thresholdField;
    
    private SlicerDimension[] slicerDimensionsField;
    
    private TimeWindow timeWindowField;
    
    /// <remarks/>
    public Threshold Threshold {
        get {
            return this.thresholdField;
        }
        set {
            this.thresholdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public SlicerDimension[] SlicerDimensions {
        get {
            return this.slicerDimensionsField;
        }
        set {
            this.slicerDimensionsField = value;
        }
    }
    
    /// <remarks/>
    public TimeWindow TimeWindow {
        get {
            return this.timeWindowField;
        }
        set {
            this.timeWindowField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
public partial class InstanceQuery {
    
    private string[] selectClausesField;
    
    private ArrayOfWhereClausesFilterFilter[] whereClausesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Column", IsNullable=false)]
    public string[] SelectClauses {
        get {
            return this.selectClausesField;
        }
        set {
            this.selectClausesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Filter", IsNullable=false)]
    public ArrayOfWhereClausesFilterFilter[] WhereClauses {
        get {
            return this.whereClausesField;
        }
        set {
            this.whereClausesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ArrayOfWhereClausesFilterFilter {
    
    private string fieldField;
    
    private string conditionField;
    
    private string valueField;
    
    private string logicField;
    
    private DurationTimeResolution timeUnitField;
    
    private bool timeUnitFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Condition {
        get {
            return this.conditionField;
        }
        set {
            this.conditionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Logic {
        get {
            return this.logicField;
        }
        set {
            this.logicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DurationTimeResolution TimeUnit {
        get {
            return this.timeUnitField;
        }
        set {
            this.timeUnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimeUnitSpecified {
        get {
            return this.timeUnitFieldSpecified;
        }
        set {
            this.timeUnitFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
public enum DurationTimeResolution {
    
    /// <remarks/>
    Day,
    
    /// <remarks/>
    Hour,
    
    /// <remarks/>
    Minute,
    
    /// <remarks/>
    Second,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
public partial class AlertInstance {
    
    private string messageField;
    
    private object itemField;
    
    private string[] ownersField;
    
    private Subscription[] subscriptionsField;
    
    private string nameField;
    
    private string priorityField;
    
    private bool enabledField;
    
    private string securityField;
    
    private string createdByField;
    
    private System.DateTime creationDateField;
    
    private bool creationDateFieldSpecified;
    
    private System.DateTime lastModifiedDateField;
    
    private bool lastModifiedDateFieldSpecified;
    
    private string extensionRefField;
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AggregationQuery", typeof(AggregationQuery))]
    [System.Xml.Serialization.XmlElementAttribute("InstanceQuery", typeof(InstanceQuery))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Owner", DataType="token", IsNullable=false)]
    public string[] Owners {
        get {
            return this.ownersField;
        }
        set {
            this.ownersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Subscription[] Subscriptions {
        get {
            return this.subscriptionsField;
        }
        set {
            this.subscriptionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string Security {
        get {
            return this.securityField;
        }
        set {
            this.securityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string CreatedBy {
        get {
            return this.createdByField;
        }
        set {
            this.createdByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime CreationDate {
        get {
            return this.creationDateField;
        }
        set {
            this.creationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreationDateSpecified {
        get {
            return this.creationDateFieldSpecified;
        }
        set {
            this.creationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime LastModifiedDate {
        get {
            return this.lastModifiedDateField;
        }
        set {
            this.lastModifiedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LastModifiedDateSpecified {
        get {
            return this.lastModifiedDateFieldSpecified;
        }
        set {
            this.lastModifiedDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string ExtensionRef {
        get {
            return this.extensionRefField;
        }
        set {
            this.extensionRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
public partial class MaxAlertsPerTimeUnit {
    
    private TimePartSimple timeUnitField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TimePartSimple TimeUnit {
        get {
            return this.timeUnitField;
        }
        set {
            this.timeUnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="positiveInteger")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
public partial class TimeDuration {
    
    private TimePart unitField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TimePart Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
public enum TimePart {
    
    /// <remarks/>
    Year,
    
    /// <remarks/>
    Quarter,
    
    /// <remarks/>
    Month,
    
    /// <remarks/>
    Week,
    
    /// <remarks/>
    Day,
    
    /// <remarks/>
    Hour,
    
    /// <remarks/>
    Minute,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM/ManagementWebService")]
public partial class Alert {
    
    private string viewNameField;
    
    private string activityNameField;
    
    private string cubeNameField;
    
    private string rtaNameField;
    
    private TimeDuration pollingIntervalField;
    
    private MaxAlertsPerTimeUnit maxAlertsPerTimeUnitField;
    
    private AlertInstance alertInstanceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string ViewName {
        get {
            return this.viewNameField;
        }
        set {
            this.viewNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string ActivityName {
        get {
            return this.activityNameField;
        }
        set {
            this.activityNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string CubeName {
        get {
            return this.cubeNameField;
        }
        set {
            this.cubeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string RtaName {
        get {
            return this.rtaNameField;
        }
        set {
            this.rtaNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
    public TimeDuration PollingInterval {
        get {
            return this.pollingIntervalField;
        }
        set {
            this.pollingIntervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
    public MaxAlertsPerTimeUnit MaxAlertsPerTimeUnit {
        get {
            return this.maxAlertsPerTimeUnitField;
        }
        set {
            this.maxAlertsPerTimeUnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/BizTalkServer/2004/10/BAM")]
    public AlertInstance AlertInstance {
        get {
            return this.alertInstanceField;
        }
        set {
            this.alertInstanceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
public delegate void AddSubscriptionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
public delegate void CreateAlertCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
public delegate void DeleteAlertCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
public delegate void GenerateEventForArtifactCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
public delegate void GetAlertCompletedEventHandler(object sender, GetAlertCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Alert Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Alert)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
public delegate void GetAlertsSummaryCompletedEventHandler(object sender, GetAlertsSummaryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetAlertsSummaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetAlertsSummaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public AlertSummary[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((AlertSummary[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
public delegate void GetCapabilitiesCompletedEventHandler(object sender, GetCapabilitiesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetCapabilitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetCapabilitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Configuration Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Configuration)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
public delegate void GetPivotViewXmlCompletedEventHandler(object sender, GetPivotViewXmlCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetPivotViewXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetPivotViewXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
public delegate void GetRelatedActivityInstancesCompletedEventHandler(object sender, GetRelatedActivityInstancesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetRelatedActivityInstancesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetRelatedActivityInstancesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public RelatedActivities Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((RelatedActivities)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
public delegate void GetReferencesCompletedEventHandler(object sender, GetReferencesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetReferencesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetReferencesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Reference[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Reference[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
public delegate void GetViewDetailsAsXmlCompletedEventHandler(object sender, GetViewDetailsAsXmlCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetViewDetailsAsXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetViewDetailsAsXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
public delegate void GetViewSummaryForCurrentUserCompletedEventHandler(object sender, GetViewSummaryForCurrentUserCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetViewSummaryForCurrentUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetViewSummaryForCurrentUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ViewSummaryList Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ViewSummaryList)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
public delegate void RemoveSubscriptionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
public delegate void UpdateAlertCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.26")]
public delegate void UpdateSubscriptionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
