//---------------------------------------------------------------------
// File: Headers.cs
//
// Sample: MessageEnrichment
//
//---------------------------------------------------------------------
// This file is part of the Microsoft BizTalk Server SDK
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//
// This source code is intended only as a supplement to Microsoft BizTalk
// Server release and/or on-line documentation. See these other
// materials for detailed information regarding Microsoft code samples.
//
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
// KIND, WHETHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
// PURPOSE.
//---------------------------------------------------------------------



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://EDI/Headers", IsNullable=false)]
public partial class Headers {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GS", typeof(HeadersGS))]
    [System.Xml.Serialization.XmlElementAttribute("ISA", typeof(HeadersISA))]
    [System.Xml.Serialization.XmlElementAttribute("UNA", typeof(HeadersUNA))]
    [System.Xml.Serialization.XmlElementAttribute("UNB", typeof(HeadersUNB))]
    [System.Xml.Serialization.XmlElementAttribute("UNG", typeof(HeadersUNG))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://EDI/Headers", IsNullable = false, ElementName = "GS")]
public partial class HeadersGS {
    
    private string gS01Field;
    
    private string gS02Field;
    
    private string gS03Field;
    
    private string gS04Field;
    
    private string gS05Field;
    
    private string gS06Field;
    
    private string gS07Field;
    
    private string gS08Field;

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string GS01 {
        get {
            return this.gS01Field;
        }
        set {
            this.gS01Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string GS02 {
        get {
            return this.gS02Field;
        }
        set {
            this.gS02Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string GS03 {
        get {
            return this.gS03Field;
        }
        set {
            this.gS03Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string GS04 {
        get {
            return this.gS04Field;
        }
        set {
            this.gS04Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string GS05 {
        get {
            return this.gS05Field;
        }
        set {
            this.gS05Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string GS06 {
        get {
            return this.gS06Field;
        }
        set {
            this.gS06Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string GS07 {
        get {
            return this.gS07Field;
        }
        set {
            this.gS07Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string GS08 {
        get {
            return this.gS08Field;
        }
        set {
            this.gS08Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://EDI/Headers", IsNullable = false, ElementName = "ISA")]
public partial class HeadersISA {
    
    private string iSA01Field;
    
    private string iSA02Field;
    
    private string iSA03Field;
    
    private string iSA04Field;
    
    private string iSA05Field;
    
    private string iSA06Field;
    
    private string iSA07Field;
    
    private string iSA08Field;
    
    private string iSA09Field;
    
    private string iSA10Field;
    
    private string iSA11Field;
    
    private string iSA12Field;
    
    private string iSA13Field;
    
    private string iSA14Field;
    
    private string iSA15Field;
    
    private string iSA16Field;
    
    private string segmentTerminatorField;
    
    private string dataElementSeparatorField;

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA01 {
        get {
            return this.iSA01Field;
        }
        set {
            this.iSA01Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA02 {
        get {
            return this.iSA02Field;
        }
        set {
            this.iSA02Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA03 {
        get {
            return this.iSA03Field;
        }
        set {
            this.iSA03Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA04 {
        get {
            return this.iSA04Field;
        }
        set {
            this.iSA04Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA05 {
        get {
            return this.iSA05Field;
        }
        set {
            this.iSA05Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA06 {
        get {
            return this.iSA06Field;
        }
        set {
            this.iSA06Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA07 {
        get {
            return this.iSA07Field;
        }
        set {
            this.iSA07Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA08 {
        get {
            return this.iSA08Field;
        }
        set {
            this.iSA08Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA09 {
        get {
            return this.iSA09Field;
        }
        set {
            this.iSA09Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA10 {
        get {
            return this.iSA10Field;
        }
        set {
            this.iSA10Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA11 {
        get {
            return this.iSA11Field;
        }
        set {
            this.iSA11Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA12 {
        get {
            return this.iSA12Field;
        }
        set {
            this.iSA12Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA13 {
        get {
            return this.iSA13Field;
        }
        set {
            this.iSA13Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA14 {
        get {
            return this.iSA14Field;
        }
        set {
            this.iSA14Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA15 {
        get {
            return this.iSA15Field;
        }
        set {
            this.iSA15Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string ISA16 {
        get {
            return this.iSA16Field;
        }
        set {
            this.iSA16Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string SegmentTerminator {
        get {
            return this.segmentTerminatorField;
        }
        set {
            this.segmentTerminatorField = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string DataElementSeparator {
        get {
            return this.dataElementSeparatorField;
        }
        set {
            this.dataElementSeparatorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://EDI/Headers", IsNullable = false, ElementName="UNA")]
public partial class HeadersUNA {
    
    private string uNA1Field;
    
    private string uNA2Field;
    
    private string uNA3Field;
    
    private string uNA4Field;
    
    private string uNA5Field;
    
    private string uNA6Field;

    [System.Xml.Serialization.XmlElement(Namespace="http://EDI/Headers")]
    /// <remarks/>
    public string UNA1 {
        get {
            return this.uNA1Field;
        }
        set {
            this.uNA1Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string UNA2 {
        get {
            return this.uNA2Field;
        }
        set {
            this.uNA2Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string UNA3 {
        get {
            return this.uNA3Field;
        }
        set {
            this.uNA3Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string UNA4 {
        get {
            return this.uNA4Field;
        }
        set {
            this.uNA4Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string UNA5 {
        get {
            return this.uNA5Field;
        }
        set {
            this.uNA5Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string UNA6 {
        get {
            return this.uNA6Field;
        }
        set {
            this.uNA6Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://EDI/Headers", IsNullable = false, ElementName = "UNB")]
public partial class HeadersUNB {
    
    private HeadersUNBUNB1 uNB1Field;
    
    private HeadersUNBUNB2 uNB2Field;
    
    private HeadersUNBUNB3 uNB3Field;
    
    private HeadersUNBUNB4 uNB4Field;
    
    private string uNB5Field;
    
    private HeadersUNBUNB6 uNB6Field;
    
    private string uNB7Field;
    
    private string uNB8Field;
    
    private string uNB9Field;
    
    private string uNB10Field;
    
    private string uNB11Field;

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public HeadersUNBUNB1 UNB1 {
        get {
            return this.uNB1Field;
        }
        set {
            this.uNB1Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public HeadersUNBUNB2 UNB2 {
        get {
            return this.uNB2Field;
        }
        set {
            this.uNB2Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public HeadersUNBUNB3 UNB3 {
        get {
            return this.uNB3Field;
        }
        set {
            this.uNB3Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public HeadersUNBUNB4 UNB4 {
        get {
            return this.uNB4Field;
        }
        set {
            this.uNB4Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string UNB5 {
        get {
            return this.uNB5Field;
        }
        set {
            this.uNB5Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public HeadersUNBUNB6 UNB6 {
        get {
            return this.uNB6Field;
        }
        set {
            this.uNB6Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string UNB7 {
        get {
            return this.uNB7Field;
        }
        set {
            this.uNB7Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string UNB8 {
        get {
            return this.uNB8Field;
        }
        set {
            this.uNB8Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string UNB9 {
        get {
            return this.uNB9Field;
        }
        set {
            this.uNB9Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string UNB10 {
        get {
            return this.uNB10Field;
        }
        set {
            this.uNB10Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string UNB11 {
        get {
            return this.uNB11Field;
        }
        set {
            this.uNB11Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HeadersUNBUNB1 {
    
    private string uNB11Field;
    
    private string uNB12Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNB1.1")]
    public string UNB11 {
        get {
            return this.uNB11Field;
        }
        set {
            this.uNB11Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNB1.2")]
    public string UNB12 {
        get {
            return this.uNB12Field;
        }
        set {
            this.uNB12Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HeadersUNBUNB2 {
    
    private string uNB21Field;
    
    private string uNB22Field;
    
    private string uNB23Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNB2.1")]
    public string UNB21 {
        get {
            return this.uNB21Field;
        }
        set {
            this.uNB21Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNB2.2")]
    public string UNB22 {
        get {
            return this.uNB22Field;
        }
        set {
            this.uNB22Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNB2.3")]
    public string UNB23 {
        get {
            return this.uNB23Field;
        }
        set {
            this.uNB23Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HeadersUNBUNB3 {
    
    private string uNB31Field;
    
    private string uNB32Field;
    
    private string uNB33Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNB3.1")]
    public string UNB31 {
        get {
            return this.uNB31Field;
        }
        set {
            this.uNB31Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNB3.2")]
    public string UNB32 {
        get {
            return this.uNB32Field;
        }
        set {
            this.uNB32Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNB3.3")]
    public string UNB33 {
        get {
            return this.uNB33Field;
        }
        set {
            this.uNB33Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HeadersUNBUNB4 {
    
    private string uNB41Field;
    
    private string uNB42Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNB4.1")]
    public string UNB41 {
        get {
            return this.uNB41Field;
        }
        set {
            this.uNB41Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNB4.2")]
    public string UNB42 {
        get {
            return this.uNB42Field;
        }
        set {
            this.uNB42Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HeadersUNBUNB6 {
    
    private string uNB61Field;
    
    private string uNB62Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNB6.1")]
    public string UNB61 {
        get {
            return this.uNB61Field;
        }
        set {
            this.uNB61Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNB6.2")]
    public string UNB62 {
        get {
            return this.uNB62Field;
        }
        set {
            this.uNB62Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://EDI/Headers", IsNullable = false, ElementName = "UNG")]
public partial class HeadersUNG {
    
    private string uNG1Field;
    
    private HeadersUNGUNG2 uNG2Field;
    
    private HeadersUNGUNG3 uNG3Field;
    
    private HeadersUNGUNG4 uNG4Field;
    
    private string uNG5Field;
    
    private string uNG6Field;
    
    private HeadersUNGUNG7 uNG7Field;
    
    private string uNG8Field;

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string UNG1 {
        get {
            return this.uNG1Field;
        }
        set {
            this.uNG1Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public HeadersUNGUNG2 UNG2 {
        get {
            return this.uNG2Field;
        }
        set {
            this.uNG2Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public HeadersUNGUNG3 UNG3 {
        get {
            return this.uNG3Field;
        }
        set {
            this.uNG3Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public HeadersUNGUNG4 UNG4 {
        get {
            return this.uNG4Field;
        }
        set {
            this.uNG4Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string UNG5 {
        get {
            return this.uNG5Field;
        }
        set {
            this.uNG5Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string UNG6 {
        get {
            return this.uNG6Field;
        }
        set {
            this.uNG6Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public HeadersUNGUNG7 UNG7 {
        get {
            return this.uNG7Field;
        }
        set {
            this.uNG7Field = value;
        }
    }

    [System.Xml.Serialization.XmlElement(Namespace = "http://EDI/Headers")]
    /// <remarks/>
    public string UNG8 {
        get {
            return this.uNG8Field;
        }
        set {
            this.uNG8Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HeadersUNGUNG2 {
    
    private string uNG21Field;
    
    private string uNG22Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNG2.1")]
    public string UNG21 {
        get {
            return this.uNG21Field;
        }
        set {
            this.uNG21Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNG2.2")]
    public string UNG22 {
        get {
            return this.uNG22Field;
        }
        set {
            this.uNG22Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HeadersUNGUNG3 {
    
    private string uNG31Field;
    
    private string uNG32Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNG3.1")]
    public string UNG31 {
        get {
            return this.uNG31Field;
        }
        set {
            this.uNG31Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNG3.2")]
    public string UNG32 {
        get {
            return this.uNG32Field;
        }
        set {
            this.uNG32Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HeadersUNGUNG4 {
    
    private string uNG41Field;
    
    private string uNG42Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNG4.1")]
    public string UNG41 {
        get {
            return this.uNG41Field;
        }
        set {
            this.uNG41Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNG4.2")]
    public string UNG42 {
        get {
            return this.uNG42Field;
        }
        set {
            this.uNG42Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HeadersUNGUNG7 {
    
    private string uNG71Field;
    
    private string uNG72Field;

    private string uNG73Field;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNG7.1")]
    public string UNG71 {
        get {
            return this.uNG71Field;
        }
        set {
            this.uNG71Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNG7.2")]
    public string UNG72 {
        get {
            return this.uNG72Field;
        }
        set {
            this.uNG72Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNG7.3")]
    public string UNG73
    {
        get
        {
            return this.uNG73Field;
        }
        set
        {
            this.uNG73Field = value;
        }
    }
}
