//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESB.BizTalkOperationsService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESB.BizTalkOperationsService.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during initialization of the BizTalk Operations Service..
        /// </summary>
        internal static string e251001 {
            get {
                return ResourceManager.GetString("e251001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving the host instance information..
        /// </summary>
        internal static string e251002 {
            get {
                return ResourceManager.GetString("e251002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving Receive Location information..
        /// </summary>
        internal static string e251003 {
            get {
                return ResourceManager.GetString("e251003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving Receive Location by Description information..
        /// </summary>
        internal static string e251004 {
            get {
                return ResourceManager.GetString("e251004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving Send Port information..
        /// </summary>
        internal static string e251005 {
            get {
                return ResourceManager.GetString("e251005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving Send Port by Description information..
        /// </summary>
        internal static string e251006 {
            get {
                return ResourceManager.GetString("e251006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving Orchestration information..
        /// </summary>
        internal static string e251007 {
            get {
                return ResourceManager.GetString("e251007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving the BizTalk System Status..
        /// </summary>
        internal static string e251008 {
            get {
                return ResourceManager.GetString("e251008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving the BizTalk Application Status for &apos;{0}&apos;..
        /// </summary>
        internal static string e251009 {
            get {
                return ResourceManager.GetString("e251009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving the Status for BizTalk Applications..
        /// </summary>
        internal static string e251010 {
            get {
                return ResourceManager.GetString("e251010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving the all the chanaged BizTalk artifacts since &apos;{0}&apos;..
        /// </summary>
        internal static string e251011 {
            get {
                return ResourceManager.GetString("e251011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving the Message Flow for Instance Id &apos;{0}&apos;.
        /// </summary>
        internal static string e251012 {
            get {
                return ResourceManager.GetString("e251012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving the Tracked Message Body for message id, &apos;{0}&apos;..
        /// </summary>
        internal static string e251013 {
            get {
                return ResourceManager.GetString("e251013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while attempting to update the receive location description..
        /// </summary>
        internal static string e251014 {
            get {
                return ResourceManager.GetString("e251014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while attempting to update the send port description..
        /// </summary>
        internal static string e251015 {
            get {
                return ResourceManager.GetString("e251015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving the live message body for message id, &apos;{0}&apos;..
        /// </summary>
        internal static string e251016 {
            get {
                return ResourceManager.GetString("e251016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving the current Orchestration Instance, &apos;{0}&apos;..
        /// </summary>
        internal static string e251017 {
            get {
                return ResourceManager.GetString("e251017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving the current Message Instance, &apos;{0}&apos;..
        /// </summary>
        internal static string e251018 {
            get {
                return ResourceManager.GetString("e251018", resourceCulture);
            }
        }
    }
}
